### PR TITLE
improved overall code structure for better readability, improved general styling, added media queries for mobile responsiveness

### PR DESCRIPTION
**Pull request by Davethadev**
Hey Divine-Sarah. My name's David and we're on the same team in the current Web3bridge cohort. I was going through some of the projects on your repo and I came across this particular project and I noticed there were a few issues with the styling and also there were no media queries so it wasn't mobile responsive. I thought it would be a nice challenge to see how much I could improve it so I got right into it and I think I've been able to improve it just a bit.
I hosted it on my github after I made the changes. Here's a link to it so you can check it out: https://davethadev.github.io/frontend-chowbetter/
Lemme know what you think about the changes I made and if you like them you could merge this pull request. So that's it. Thanks and bye for now.

### CODE REVIEW

**Comment by eadewusic** [comment]
Hey devs,

Welldone. Can I join in?

**Comment by Davethadev** [comment]
Sure I guess. Would you like to create an issue and contribute or?

P.S: I'm not the author or maintainer. Just found the repo a while back and decided to contribute. I'm guessing they wouldn't mind if you decide to do same

**Comment by eadewusic** [comment]
It was our project for an hackathon. I'll contribute

**Comment by Davethadev** [comment]
Oh alright.

**Pull request merged**
